server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          #git仓库，配置github应该独立，与代码仓库分开
          uri: https://github.com/Peishujuan/peishujuan-springcloud-demo
          #配置搜索目录
          search-paths:
            - configfiles
            - #默认拉取配置的git分支
          default-label: master
          #如果你的git不公开就需要设置密码
          #password:
      #从哪个分支去拉取 配置文件
      label: spring-cloud-config